apiVersion: v1
kind: Service
metadata:
  name: coordinates-api-svc
  labels:
    app: coordinates-api
spec:
  type: NodePort
  selector:
    app: coordinates-api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    name: coordinates-api


